### ISSUE TITLE
link parameter can not be used in echr-extractor

### ISSUE THREAD

**Issue by NagisYuksel** [maastrichtlawtech/extraction_libraries#4] opened 2023-09-13 11:21 UTC
I enter the URL of the advanced search I made on the HUDOC website into the "link" parameter, which is a parameter of the get_echr and get_echr_extra functions in ECHR-extractor, but I get attached error.

![image001](https://github.com/maastrichtlawtech/extraction_libraries/assets/142304733/b59e7a4e-a607-4377-949b-8cc29d28fec8)

**Comment by shashankmc** [comment] 2023-09-20 07:40
Thanks for trying the extractor out. I've tried to replicate your error and invalid decimal literal goes away when %20 and %22 are replaced with <space> and " respectively. It does produce a new error. 

@Cloud956 Could you please look into this? The issue persists even if the steps are followed as provided in the appendix.

**Comment by Cloud956** [comment] 2023-09-25 14:07
@NagisYuksel  I have published an update which should resolve your issues, please update your package and test it out.

The main problem seems to be caused by the use of "" brackets in the search fields, like in your (NOT "has been a violation of Article 6") 

This has now been fixed, but only for the 'Text' field. The " brackets will still cause issues for other parameters, but from what I saw on the HUDOC website you only might really need it for the 'Text' field of the search. If you need to use the brackets in other search fields, please reach out again and raise another issue. 

I will close the issue, as it is resolved with the new update.

**Comment by NagisYuksel** [comment] 2023-10-03 07:25
*Thank you very much for your interest, but when I write the code
below, I get an error again, I couldn't understand what I did wrong.*

import echr_extractor as echr
echr_link="https://hudoc.echr.coe.int/eng#{%22fulltext%22:[%22(NOT%20\%22has%20been%20a%20violation%20of%20Article%206\%22)%20AND%20(\%22has%20been%20no%20violation%20of%20Article%206\%22)%22]}
<https://hudoc.echr.coe.int/eng#%7B%22fulltext%22:[%22(NOT%20%5C%22has%20been%20a%20violation%20of%20Article%206%5C%22)%20AND%20(%5C%22has%20been%20no%20violation%20of%20Article%206%5C%22)%22]%7D>"
df, json = echr.get_echr_extra(link=echr_link)

--------------------------------------------------------------------------------------------

C:\Users\nagihan.yuksel\PycharmProjects\pythonProject2\venv\Scripts\python.exe
C:\Users\nagihan.yuksel\PycharmProjects\pythonProject2\main.py
Traceback (most recent call last):
  File "C:\Users\nagihan.yuksel\PycharmProjects\pythonProject2\main.py",
line 6, in <module>
    df, json = echr.get_echr_extra(link=echr_link)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nagihan.yuksel\PycharmProjects\pythonProject2\venv\Lib\site-packages\echr_extractor\echr.py",
line 67, in get_echr_extra
    df = get_echr(start_id=start_id, end_id=end_id,
start_date=start_date, end_date=end_date, verbose=verbose,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nagihan.yuksel\PycharmProjects\pythonProject2\venv\Lib\site-packages\echr_extractor\echr.py",
line 27, in get_echr
    df = get_echr_metadata(start_id=start_id, end_id=end_id,
start_date=start_date, end_date=end_date,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nagihan.yuksel\PycharmProjects\pythonProject2\venv\Lib\site-packages\echr_extractor\ECHR_metadata_harvester.py",
line 171, in get_echr_metadata
    META_URL = link_to_query(link)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nagihan.yuksel\PycharmProjects\pythonProject2\venv\Lib\site-packages\echr_extractor\ECHR_metadata_harvester.py",
line 119, in link_to_query
    link_dictionary = eval(link[start:])
                      ^^^^^^^^^^^^^^^^^^
  File "<string>", line 1
    {%2
     ^
SyntaxError: invalid syntax

Process finished with exit code 1


Piotr Lewandowski ***@***.***>, 25 Eyl 2023 Pzt, 17:07
tarihinde şunu yazdı:

**Comment by shashankmc** [comment] 2023-10-03 07:30
Aren't there like 2 links for the variable echr_link?

**Comment by NagisYuksel** [comment] 2023-10-03 08:11
I'm trying to get the following search result:

https://hudoc.echr.coe.int/eng#{%22fulltext%22:[%22(NOT%20\%22has%20been%20a%20violation%20of%20Article%206\%22)%20AND%20(\%22has%20been%20no%20violation%20of%20Article%206\%22)%22]}


Shashank ***@***.***>, 3 Eki 2023 Sal, 10:30 tarihinde şunu
yazdı:

**Comment by Cloud956** [comment] 2023-10-03 08:43
@NagisYuksel  I just pushed a new version of the package, can you check if it works now?

**Comment by NagisYuksel** [comment] 2023-10-03 09:32
Yes it worked, but while HUDOC showed 693 results, the code showed 117993
results. Could it be faulty?

Piotr Lewandowski ***@***.***>, 3 Eki 2023 Sal, 11:43
tarihinde şunu yazdı:

**Comment by Cloud956** [comment] 2023-10-03 10:13
You are correct, I pushed another update. Please check it out and test if all works now.

**Comment by NagisYuksel** [comment] 2023-10-03 11:32
It gave 117993 results again. (with version 1.0.38)

Piotr Lewandowski ***@***.***>, 3 Eki 2023 Sal, 13:13
tarihinde şunu yazdı:

**Comment by Cloud956** [comment] 2023-10-03 11:53
Pushed another update, please check this one out.

**Comment by NagisYuksel** [comment] 2023-10-03 12:18
Yes, it worked like that, I have one more question, it did not work when I
selected only Grand Chamber and Chamber in the menu on the left. If it is
possible to fix it, can you please contact me when you have time? I took up
a lot of your time, I'm sorry.

Piotr Lewandowski ***@***.***>, 3 Eki 2023 Sal, 14:54
tarihinde şunu yazdı:

**Comment by Cloud956** [comment] 2023-10-03 12:46
Pushed another one out, please test it out.

**Comment by NagisYuksel** [comment] 2023-10-03 13:25
I got the following error:
INFO:root:--- STARTING ECHR DOWNLOAD FOR  ---
Traceback (most recent call last):
  File "C:\Users\nagihan.yuksel\PycharmProjects\pythonProject6\main.py",
line 3, in <module>
    df, json = echr.get_echr_extra(link=echr_link, save_file='y')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\nagihan.yuksel\PycharmProjects\pythonProject6\venv\Lib\site-packages\echr_extractor\echr.py",
line 67, in get_echr_extra
    df = get_echr(start_id=start_id, end_id=end_id, start_date=start_date,
end_date=end_date, verbose=verbose,

 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\nagihan.yuksel\PycharmProjects\pythonProject6\venv\Lib\site-packages\echr_extractor\echr.py",
line 27, in get_echr
    df = get_echr_metadata(start_id=start_id, end_id=end_id,
start_date=start_date, end_date=end_date,

 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\nagihan.yuksel\PycharmProjects\pythonProject6\venv\Lib\site-packages\echr_extractor\ECHR_metadata_harvester.py",
line 185, in get_echr_metadata
    META_URL = link_to_query(link)
               ^^^^^^^^^^^^^^^^^^^
  File
"C:\Users\nagihan.yuksel\PycharmProjects\pythonProject6\venv\Lib\site-packages\echr_extractor\ECHR_metadata_harvester.py",
line 149, in link_to_query
    query_elements.append(funct(key, vals))
                          ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

Piotr Lewandowski ***@***.***>, 3 Eki 2023 Sal, 15:46
tarihinde şunu yazdı:

**Comment by NagisYuksel** [comment] 2023-10-03 13:26
The link parameter is as follows:

echr_link="https://hudoc.echr.coe.int/eng#{%22fulltext%22:[%22(\%22has%20been%20a%20violation%20of%20Article%206\%22)%20AND%20NOT(\%22has%20been%20no%20violation%20of%20Article%206\%22)%22],%22sort%22:[%22docnamesort%20Ascending%22],%22documentcollectionid2%22:[%22GRANDCHAMBER%22,%22CHAMBER%22]}"


Nagihan Ünal ***@***.***>, 3 Eki 2023 Sal, 16:25 tarihinde şunu
yazdı:

**Comment by Cloud956** [comment] 2023-10-03 13:32
Its because of the sorting.  Is it crucial for you to have the metadata download also sorted? I pushed an update which ignores sorting for now.

**Comment by NagisYuksel** [comment] 2023-10-03 13:41
Sorry, I clicked there by mistake.Of course, the sorting is not
important. Thank you very much for your effort.


Piotr Lewandowski ***@***.***>, 3 Eki 2023 Sal, 16:33
tarihinde şunu yazdı:

**Comment by Cloud956** [comment] 2023-10-03 13:45
If it is important, I think it would be easier to do it after the extraction is done and you have a dataframe, so I will skip sorting in this package.

**Comment by NagisYuksel** [comment] 2023-10-03 14:03
Yes I think so too, thank you very much.

Piotr Lewandowski ***@***.***>, 3 Eki 2023 Sal, 16:45
tarihinde şunu yazdı:

**Comment by Cloud956** [comment] 2023-10-04 15:33
@NagisYuksel I pushed an update to the package with a new way to download echr data. Instead of the link to the website, you can use the API call which the website is using to get the search data. This method should 100% not break and does not include any sorting. Full documentation at https://pypi.org/project/echr-extractor/1.0.43/ . I think this should resolve your problems, I'm closing this issue.

**Closed as completed by Cloud956** 2023-10-04 15:33 UTC
Labels: bug
